### ISSUE TITLE
[Suggestion] Wifi passwords

### ISSUE THREAD

**Issue by navid-zamani** [mrrfv/open-android-backup#72] opened 2023-08-10 16:38 UTC
**[Hardware- and OS-independent]**

Hey, you said that suggestions for what to backup are welcome.

I used to use Huawei Backup. Which backs up the wifi passwords too. (And the system settings, among everything else.)

I don’t know if Android even lets users do this without root, but it would be super-handy. E.g. so I don’t have to ask everyone for their password again, which might be awkward or their openness or boss/spouse/admin may have changed.

If you know for certain, that there is no way to access that data without root, and you don’t support root (because in that case, just `dd`ing the block device from recovery would be the most reliable backup), just mark this as impossible, and I know not to think about it anymore.

**Comment by navid-zamani** [comment] 2023-08-10 16:39
Btw: should I open a separate issue for backing up Android (system) settings? (Like e.g. UI size, or night mode start and stop times, etc.) (Or is that just another app from Android’s perspective, and already covered by app backup?)

**Comment by mrrfv** [comment] 2023-08-11 10:35
This is indeed out of scope because root is needed. The reason Huawei Backup is able to backup your WiFi passwords is because it's a privileged app. Also a duplicate of #31.

> Btw: should I open a separate issue for backing up Android (system) settings? (Like e.g. UI size, or night mode start and stop times, etc.) (Or is that just another app from Android’s perspective, and already covered by app backup?)

This might be doable. If I remember correctly, Android stores system settings in a simple key/value database that can be read and written to by apps given enough permissions. I'll look into this later - feel free to open another issue for that.

**Closed by mrrfv** 2023-08-11 10:35 UTC
Labels: bug
