### ISSUE TITLE
On MacOS, restoring fails

### ISSUE THREAD

**Issue by petefoth** [mrrfv/open-android-backup#124] opened 2024-07-04 09:40 UTC
## Device info

Manufacturer: Sony
Android version: 14
Custom ROM/rooted? LineageOS for microG
Model: XZ1 Compact `lilac`

## System info

Available disk space: 68GB
Operating system: MacOS Monterey 12.7.5

---
- Backup works fine: the backup file is created: `/Users/pete/Downloads/Open_Android_Backup_v1.0.18_Bundle/open-android-backup-07-04-2024-09-36-16.7z`
- When I try to restore  I see the following error after I have selected the backup file
```
stat: illegal option -- -
usage: stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file ...]
Less than  KB of free space available on the current directory - not enough to extract this backup.
Please free up some space and try again.
```
- there is plenty of disk space: 
```
$ df -h
Filesystem     Size   Used  Avail Capacity   iused  ifree    %iused  Mounted on
/dev/disk1s5s1 234Gi  14Gi   56Gi    1%     502387 589666960    0%   /
```
- I see the same error
    - Whether I specify a fully qualified file name or just the filename
    - Restoring to the same device as backed up, a different device of the same model, and a different model Google Pixel 4a `sunfish`. All devices running  LineageOS for microG v21.0 

Let me know if you would like any further information

**Comment by mrrfv** [comment] 2024-07-04 10:54
A fix has landed in the master branch. Please pull or download an [unstable bundle](<https://github.com/mrrfv/open-android-backup/releases/download/latest/Open_Android_Backup_Unstable_Bundle.zip>), then let me know if the issue is resolved.

**Comment by petefoth** [comment] 2024-07-04 12:34
That worked - thanks.

Should I close this issue, or do you want to wait until the fix is in a stable build?

**Comment by mrrfv** [comment] 2024-07-04 17:40
Closing it now is okay. I'll try to make another release later today since the project has accumulated some significant fixes for macOS since the last one.

**Closed by mrrfv** 2024-07-04 17:40 UTC
Labels: bug
